spring.application.name=HogwartsHW
spring.datasource.url= jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username= VarvaraAdmin
spring.datasource.password= 04121992
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
